services:
    database:
        image: postgres:15-alpine
        ports:
            - 5432:5432
        environment:
            - POSTGRES_DB=food
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        #volumes:
        #    - ./data/postgres:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-food}"]
            interval: 10s
            retries: 5
            timeout: 10s
        expose:
            - 5432

    api:
        build:
            context: .
        ports:
            - 8000:8000
        depends_on:
            database:
                condition: service_healthy
        environment:
            - DB_HOST=database
            - DB_PORT=5432
            - DB_USER=postgres
            - DB_PASS=postgres
            - DB_BASE=food
