apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: food-autoservice-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: food-autoservice
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
